server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,industries.werwolf

# Open-in-view is only needed if you use lazy-loaded entities in your Flow views.
spring.jpa.open-in-view=false

# Initialize the JPA Entity Manager before considering data.sql so that the EM can create the schema and data.sql contain data
spring.jpa.defer-datasource-initialization = true


logging.level.sql=warn
## shows bind parameter values when set to trace
logging.level.org.hibernate.orm.jdbc.bind=error
logging.level.org.springframework=warn
logging.level.org.vaadin=warn
logging.level.org.flywaydb.core.internal.command=warn